### PR TITLE
add moment object support for start and end attributes and correspond…

### PR DESCRIPTION
**Pull request by andrewmtoy**
…ing test

### CODE REVIEW

**Comment by andrewmtoy** [comment]
Thanks for this repo, its been really helpful!

**Comment by josemarluedke** [comment]
Hello there! Thanks for the PR.

I'm wondering what is the goal with this change? Also not sure if it will break existing apps using this addon.

**Comment by andrewmtoy** [comment]
Hi @josemarluedke sorry for the late response.
The [daterangepicker](http://www.daterangepicker.com/#options) library accepts Date object, Moment object, or strings for the following options: startDate, endDate, minDate, and maxDate. 

When I tried to pass in moment objects to the startDate and endDate attributes of this component, I found that when you change the date range, the moment objects are converted to strings because of the invocation of the format method.  

I added a corresponding integration test for this change, and I confirmed that all the tests pass so I don't believe that other apps that use this will break.   

I could/should also add an additional integration test to verify that this wrapper handles strings correctly as well.

I'll also check and add tests for minDate and maxDate attributes.

**Comment by josemarluedke** [comment]
@andrewmtoy would you mind rebasing?

**Comment by andrewmtoy** [comment]
Closing pr for now.  I'll reopen this when I've updated with additional tests.

**Pull request closed without merging**
