### PR TITLE
Upgrade to ember v1.12.0 and ember-cli v0.2.7

### PR DESCRIPTION
**Pull request by malchak**
This PR updates the ember and ember-cli version, along with all other associated version dependencies.

Also included are changes to the location of the core addon logic.  Previous, this code was placed under the `/app/components` folder, but has now been moved to the `/addon/components` folder in order to follow community established conventions.  The new `app/components/date-range-picker.js` file is now only responsible for exporting the component into an app's namespace.

Also there was a Chrome bug related to the use of a prototype extension being defined inside the `date-range-picker.js` component file.  That computed property has been changed, and now uses `Ember.computed` instead.

### CODE REVIEW

**Comment by gregjopa** [comment]
This PR looks good to me. To verify this change I did the following:
1. git clone https://github.com/malchak/ember-cli-daterangepicker.git
2. npm install
3. bower install
4. ember s
5. Went to http://localhost:4200/ and confirmed the default date range picker component works as expected.

**Comment by malchak** [comment]
@josemarluedke Any timeline on when you'll be able to review this?  Thanks!

**Comment by josemarluedke** [comment]
@malchak Now. :D

**Comment by josemarluedke** [comment]
Awesome @malchak! Really good refactoring. Just released v0.0.7 on npm, not sure if it should be v0.1.0, let me know if you guys think we should bump to v0.1.0. 

Thank you very much for your contributions.

**Comment by malchak** [comment]
@josemarluedke Thanks, no problem!  I have some other things that I'd like to submit PRs for, perhaps after that a v0.1.0 would be appropriate.

**Pull request merged**
